### ISSUE TITLE
[BLM] High Fire II to Flare Suggestion

### ISSUE THREAD

**Issue by GSchmitt709** [daemitus/XIVComboPlugin#100]
Make it 2 options

Option 1 :
High Fire II turns into Flare when in Astral Fire with 1 or less Umbral Hearts

 if (level >= BLM.Levels.Flare && gauge.InAstralFire && (gauge.UmbralHearts <= 1 || LocalPlayer?.CurrentMp < 3800))

Option 2 :
High Fire II turns into Flare when in Astral Fire and under the effect of Enhanced Flare.

if (level >= BLM.Levels.Flare && gauge.InAstralFire && (gauge.UmbralHearts == 1 || LocalPlayer?.CurrentMp < 3800 || HasEffect(BLM.Buffs.EnhancedFlare)))

**Comment by Grammernatzi** [comment]
So it's worth mentioning that for this, you'd also want to check if swiftcast/triplecast are up, since if you use a third HF2 instead while they're up, it'd be a DPS loss. Also, if you use Fire 2 three times (before you have High Fire 2), I believe it's either DPS neutral or a DPS loss. And, additionally, you need to flare early before the mobs die instead of another HF2, or that's also a DPS loss (so you'd need to still keep flare on your bar). The third high fire 2 has to be carefully done in order for it not to be a DPS loss, which is why the feature is currently on the more braindead, consistent rotation it is on right now. The second option should be okay if people know what they're doing with it (and if it has clauses for swiftcast/triplecast), I just figured to post this to let people know it's not as simple as just 'extra HF2 = more damage'.

**Comment by kaedys** [comment]
I tend to agree that the current combo is sufficient, but I also don't really disagree with having it split into two options (or having a sub-option `Use Flare as soon as you have Enhanced Flare`, or the inverse).  This mod takes it as a given that the options and consolidations it grants will not always be optimal.  In this case, if one is _really_ interested in perfectly optimizing their AoE damage (but really, so few situations where that's properly needed), they can either disable these combos, or also keep Flare on their bars and manually cast it even at 2 Umbral Hearts if need be.

**Comment by Grammernatzi** [comment]
I'm obviously fine with the idea of it being an option. It's just that I've gotten quite a few people going 'the balance has that as their rotation even though in the FAQ they literally say it's only marginally better and requires a lot of caveats'. So it's gotten slightly frustrating, but at least since I added the option in my own version, that's died down.
