### ISSUE TITLE
[Optimality] Some suggestions for Ninja,Warrior and Monk

### ISSUE THREAD

**Issue by ksledu** [daemitus/XIVComboPlugin#101]
Hi,Mr Daemitus, Thanks for giving us a great plugin. I main play ninja ,warrior and monk.  I had used a few Xivcombo modified edition, I prefer your plugins due to less memory consumption and less FPS drop-off  in game . I have some suggestions for current plugins. No offense.  some suggestions are from another similar plugins.

**Ninja**:  
please add Huraijin into main combo if huton buff is not present (buff timer=0).
![image](https://user-images.githubusercontent.com/96337656/150478582-4cba3915-af03-42b8-a506-6c5b4c84943f.png)

**Warrior**:

Option 1: In 6.0 endwalker, only Fell Cleave(Inner Chaos) and Decimate(Chaotic Cyclone) cost the Beast Gauge. So warrior is no longer to accumulate gauge over 50. but the overcap logic of plugin is that do not use fell cleave and decimate until 90. but in some points, this logic will make an conflict with main combo even gauge already reached 90. which it would put main combo skill into first priority rather than Fell Cleave/ Decimate. the result is main combo skills (Maim or Storm's Path) make  gauge overcap 10 or 20 besast.  the suggestion is that can you adjust overcap setting from 90 to 50 or 70 in case conflict with main combo. please take a look as picture below

![image](https://user-images.githubusercontent.com/96337656/150481240-0432c7a8-b62d-4245-9354-ff11586222e7.png)

Option 2: Please add this feature in to current plugins
![image](https://user-images.githubusercontent.com/96337656/150481375-e5b2b53e-6ac2-4b22-9e0d-c1f81fd5484b.png)

**Monk**:
Please add Option: 'Twin Snakes' changes into 'True Strike' if you have the 'Disciplined Fist' buff > 5 seconds.

Thank you for be patient with me ^_^

**Comment by kaedys** [comment]
The overcap feature uses Fel Cleave (or Decimate) when the next combo move would cause the gauge to _exceed_ 100.  Warriors do _not_ use their gauge immediately at 50, they still want to pool it for buff windows as much as possible.  Having the logic immediately use it at 50 would waste this potential.  The existing overcap features work precisely as advertised and are, imo, plenty sufficient. The entire point of them is purely to prevent you from using a combo move that would overcap your gauge.  It's also worth noting, if you were under this mistaken impression, that using Fel Cleave or Decimate does _not_ interrupt the melee combo, so you can use it between combo abilities without resetting that combo.

As for Orogeny, that's an oGCD, and really should just be cast yourself.  I guess I don't necessarily see any dissonance in this mod auto-casting oGCDs, though, given some of the other combos it provides.  Still, a bit too one-button for my tastes.

For the monk buff, I guess that depends on how much Daemitus wants to take this down the road of making rotational decisions.  The primary complexity to the Monk rotation is using Twin Snakes when the buff is less than ~6-7s, and using Demolish when the bleed is less than about 4-5s, and otherwise using True Strike and Snap Punch, respectively.  Personally, I think an argument could made for these, given that the mod already has a Dragon Kick/Bootshine option, and other jobs have similar consolidation options (Dancer being a notable example, with the entire 4-button RNG combo being reduced to a single button).  Ninja also just got an Aeolian Edge/Armor Crush merger.  Personally, I think it's a mistake to have a mod make a decision between two abilities with different positionals on them, but it wouldn't be the first time the mod has that (Ninja's above, as well as Reaper Gibbet/Gallows enhancement logic)

**Comment by Grammernatzi** [comment]
I personally rather dislike auto-upkeep features (including the new NIN one), and don't really consider the Dragon Kick/Bootshine option to be one, since that's more along the lines of Heavy Shot to Straight Shot, IMO. However, ultimately it's up to Daemitus and if he wants to add them or not. Orogeny, maybe, since it's just aoe and that only really matters for dungeons.

**Comment by daemitus** [comment]
Theres like 4-5 buttons that need pressing on warrior, if you don't count mitigation. There's no need to further combine things.
I recommend throwing a bar-toggle macro on like, mouse 5, then you can switch between a single target and aoe bar. No need to have everything showing all the time.

Ninja got added because they did the work for me (mostly). 

I'm likely to not touch anything else in the monk single target rotation, it being as complicated as it is. Not without another PR anyways.

**Comment by kaedys** [comment]
I wouldn't necessarily be opposed to a monk combiner for each form, as long the player is still hitting the form buttons in order.  But I also don't see a pressing need for it.  I do see a bit of a distinction between such monk form options and the buff upkeep features in other jobs (like the Ninja one above), mostly from the perspective of commonality.  A warrior, as well as most other jobs with a similar 30s buff, has a combo with a single deviation, just on the final ability, in it for their buff twice a minute.  Otherwise, they just use their normal damage combo.

Monk, on the other hand, technically has an 18-button-long combo sequence, as they need to deviate their first and second buttons every other combo and their third button every third combo.  So AAA BBB AAB BBA AAB BBB repeat.  I also honestly don't see much of a difference between those and the Bootshine/Dragon Kick combiner.  Like True Strike/Twin Snakes, you simply alternate between the two.  Heavy Shot/Straight Shot isn't quite as comparable, simply because it's an RNG proc that you'd otherwise have to react to, rather than a direct A then B then A then B sequence.

The major hesitation I have, however, is that when the mod is making the decisions about which ability to cast, the player is much less likely to be as _aware_ of which ability comes next.  Since the 3rd ability in that sequence has a positional, and it differs between the two options, it's highly likely that the player will miss positional more often with such an option.  Unless they're keeping an eye on the bleed themselves, or counting combos, most likely they'll just stand on the flank and accept the 60p loss on every third Coeurl attack.

But then, we have the Ninja option already, as well as a Reaper option for combining Gibbet and Gallows, and both of those have the same issue, so /shrug.  I guess it'd be up to the player in such a situation as to how they want to handle that, by either keeping the option off, having some other method of tracking which position they need to be in, or simply accepting the potency loss.

I get the lack of inclination to go about implementing it yourself, though.  In that context, what are the minimums for a PR?  I already opened one in regards to a Reaper change a while back, and while that PR was closed, I believe you used most of the code from it in the final implementation.  Was that PR sufficient for submission, or were there further things needed on it to minimize the bother such things put on you?  I ask not just in the context of this proposed Monk change, but any other feature requests that might come along (like, for example, #110 that I opened during a wonderful bout of insomnia this morning).

**Comment by daemitus** [comment]
In general, just match the existing styling. If I'm already mucking around
in that job, odds are I'll just copy-paste it in, like your previous one.
Or if its close enough I'll pull it in and make it look like how I want to.

**Comment by daemitus** [comment]
Regarding auto-upkeep. ehhhh whatever. It depends? Theres enough NIN
garbage going on otherwise. I've got a WAR upkeep for personal use, I can't
really hate when I'm doing it myself.

**Comment by Grammernatzi** [comment]
I've done a ton of work on Monk to make a combo that doesn't really think for you and saves a lot of buttons (while also keeping positionals separate), but it's still experimental and undergoing changes. It also is far too complex for this fork, IMO.  I think a simple solution for Monk just can't really be done, but that's fine. The simple changes added already save a ton of buttons on the job.

**Comment by kaedys** [comment]
Ya, I read over the description on your fork and was a bit reserved on how it appeared it would play out in practice, tbh.  Rather than a button per form, you instead condensed the "normal" rotation into 2 buttons, one that scrolled through the "A" ability in each form and one that scrolled through the "B" ability in each form.  ie. one button combines Dragon Kick, Twin Snakes, and Demolish, while the other combines Bootshine, True Strike, and Snap Punch.  It's essentially the same rotation as above, in that you still have to remember, for each button press, which ability needs to come next, the A or the B for that form.  It's just that instead of hitting those across 6 buttons, the mod remembers which form you're in, and you just have to hit it across 2 buttons.  Except now you also need to remember which form you're in, without the physical shift across keys to act as an analog of the form shifting.

To be honest, I'm not sure but that that's _more_ complex.  Without the physical analog of the form sequence, but still _with_ a requirement that you know which form you're in and specifically pick one or the other button as appropriate for that form, you need some other means to track which form you're in.  And I've yet to find a mod that visually displays it the way I'd like.  DelvUI, for example, just has a text box on their job gauge that writes out the name of the form, and I'm left to remember the name sequence of the forms.  In the heat of battle, whilst dodging raid mechanics, I'm busy thinking 'Is Raptor the second or the third?'  I have an open feature request for a better display element.  Personally, I'd rather have a bar with 3 segments, each a customizable color, that visually shift, left to right, as you move through the forms.  In Raptor form?  The 2nd block on the bar (or pip, if it's more like one of JobBar's diamond gauges) lights up.  Now at least you have a _visual_ analog to replace the physical one.

As it currently stands with your feature, every GCD you need to think "Ok, which form am I in.  And then, of the two abilities in that form, which one do I need to cast?  And which button was that on again?"  Of those, the last question is probably the easiest, since you've logically structured the (de)buff appliers on one button, and the higher potency attacks on the other.  But it still complicates matters, especially if Perfect Balance throws the first two out of sync.  Now, instead of your sequence being, say, 123 s1s2s3 12s3 s1s23 12s3 s1s2s3 repeat, it's 111 222 112 221 112 222 repeat.  You still have to remember which form you're in and which button to press in that form, so I'm not sure it's truly buying you much.

And then it becomes, imo, worse with the additional conditionals.  In Perfect Balance, you now have 4 buttons instead of 2, with either Demolish or Twin Snakes shifting to the other button from usual (or potentially both buttons intelligently selecting between them?  Description unclear, and I've not tested it), and then Dragon Kick and Bootshine shifting to entirely separate buttons, one of which (Form Shift) is almost never used during normal rotation.  And then during Formless Fist, another shift happens, but it's completely different.  Demolish moves to Perfect Balance, rather than it's combo button (or the other one) it had during Perfect Balance.  Dragon Kick moves to True Strike, vs. being on Perfect Balance while PB is up.  Bootshine remains on Form Shift, but potentially shifts to Snap Punch depending on settings.

It's all extremely complex logic.  And while I commend you for putting it together, I honestly think it might be simpler just to learn the normal 6 buttons rather than this 3-separate-sets of which button goes where and how to remember which button to press at any given time.

What I'd realistically be going for (and how I'd implement it if I PR'd it here) is just adding 2 additional combos to echo the Bootshine feature: Twin Snakes becomes True Strike if you have more than 6s of Twin Snakes remaining, and Demolish becomes Snap Punch if your target has more than 6s of your Demolish remaining (this also notably allows you to retain True Strike and Snap Punch on your bars separately, for if, for example, the boss will disappear in less than 3 GCDs, or you have some other reason to skip your buff refresh).  The player still makes the decision about which form they are pressing, and thus still has the physical analog of moving through the 3 forms by pressing 3 different buttons in sequence.

As for the positionals, as above, I think that ultimately lands on the player how they want to handle it.  IMO, it's an easier task, given current mods, to figure out which position you need to be at than figure out which form you're in (for Monk, you just need a timer bar for Demolish,.  For Rogue, a timer bar for Huoton.  For Reaper, you need the icons or some other way to track which Soul Reaper ability is currently empowered), versus when all of them have been condensed into one (or two) buttons, but it's still a thing.  Begs the question whether it might not be worth having a "positional helper" mod.  Could take several forms, but at its most basic, it's a major grievance of mine that positional attacks do not indicate their position requirement on their icon, either with a colored border (say, red = rear, yellow = flank) or via a corner letter ("R" or "F", ideally color-coded themselves).  It'd be much easier to visually see where you need to be if the icons indicated it in a quickly-visually-parsable manner.

**Comment by kaedys** [comment]
Whelp, we've got two PRs for the Monk piece of this: #111 and #112.  Could go with either or both, though if it's with both, we'll probably need to add Conflict tags to the two sets (I believe @Grammernatzi's also needs them versus the existing Dragon Bootshine feature).

**Comment by Grammernatzi** [comment]
Nah, mine already worked with it. But, I don't want to make it too hard for Dae, as if both were added, there'd need to be a lot of code added to mine, too. So, to make it simpler, I'll close the request for now, I don't want to add too much to his plate at the moment.

**Comment by Grammernatzi** [comment]
> I honestly think it might be simpler just to learn the normal 6 buttons rather than this 3-separate-sets of which button goes where and how to remember which button to press at any given time.

Also, in regards to this, to be fair, the combo was not to make anything easier. It was to simply reduce the amount of buttons, as I make a lot of features for disabled people that allow them to play the game with less buttons without actually simplifying things, so that they can still enjoy the game without having to resort to features that do all the thinking for them (like a certain other fork I won't name). The new combos I just added save less buttons, but are simpler to understand and use, for sure.

**Comment by daemitus** [comment]
With the current monk features, no to orogeny, and war overcap fine as it is, i think we're good to close this for now. 

Please open a new issue if I missed anything.
