### ISSUE TITLE
Now taking requests for Endwalker combos

### ISSUE THREAD

**Issue by daemitus** [daemitus/XIVComboPlugin#11]
If you think a combo needs to be altered or added for EW, please let me know. 

Current work completed:
- AST
  - **NEW** AstrologianMinorArcanaPlayFeature: Minor Arcana into Crown Play
- BLM
  - BlackFireFeature: updated for Paradox
  - BlackEnochianFeature: simplified to swap between fire4/blizzard4. Should revisit for sync'd play.
- BRD
  - No changes.
- DNC
  - DancerFanDanceCombo: updated to include FanDance4
  - DancerDanceStepCombo: updated to include Tillana
  - DancerSingleTargetMultibutton: updated for new effects
  - DancerAoeMultibutton: updated for new effects
  - **NEW** DancerDevilmentFeature: Devilment into Starfall Dance
- DRG
  - DragoonBOTDFeature: removed, BOTD is a trait.
  - DragoonFullThrustCombo: updated for Heavens' Thrust
  - DragoonChaosThrustCombo: updated for Chaotic Spring
  - DragoonCoerthanTormentCombo: updated for Draconian Fury
- DRK
  - Nothing to do. Merge the new Shadowbringer skill with something?
- GNB
  - GunbreakerGnashingFangCombo: removed, now an automatic combo
  - GunbreakerGnashingFangCont: updated for combo removal
  - GunbreakerFatedCircleFeature: updated for 3 charges
  - **NEW** GunbreakerBurstStrikeCont: Burst Strike into Hypervelocity
- MCH
  - MachinistSpreadShotFeature: updated for Scattergun
  - MachinistHotShotDrillFeature: now with Chainsaw
- MNK
  - **NEW** MonkHowlingFistMeditationFeature: aoe chakra spender defaults to Meditation, like the single target does.
- NIN
  - NinjaAssassinateFeature: removed, now an upgrade.
  - **NEW** NinjaBunshinKamaitachiFeature: Bunshin into Phantom Kamaitachi
  - **NEW** NinjaHuraijinRaijuFeature: Huraijin into Raiju when available
- PLD
  - PaladinRequiescatCombo: updated for confit blade combo
  - PaladinConfiteorFeature: updated for confit blade combo
- RDM
  - RedMageVerprocCombo: updated for Verthunder3/Veraero3, Verflare/Verholy changes. Included Resolution combo. Needs gauge work.
- RPR
  - **NEW** ReaperSliceCombo
  - **NEW** ReaperScytheCombo
  - **NEW** ReaperEnshroudCommunioFeature
- SAM
  - **NEW** SamuraiHyosetsuCombo: new aoe combo
  - **NEW** SamuraiIkishotenNamikiriFeature: Ikishoten to Ogi Namikiri to Kaeshi Namikiri
  - SamuraiThirdEyeFeature: removed, seigan is gone, third eye was reworked.
- SCH
  - No changes.
- SGE
  - Difficult to do anything with Eukrasian what-if scenarios.
- SMN
  - SummonerDemiCombo: removed
  - SummonerBoPCombo: removed
  - The rest will need likely need gauge rework.
- WAR
  - **NEW** WarriorPrimalRendFeature: Inner Beast and Steel Cyclone into Primal Rend when available.
- WHM
  - Nothing to do.

**Comment by AkiraChisaka** [comment]
MCH - Forbidden Knowledge: Automatically selecting Drill / Air-Anchor to use should also select Chainsaw

RDM: New combo finisher Resolution might need to be binded to Scorch

SGE: Make it possible for a 3 buttons to be Kardia into special action? So like, replace a emote into the Kardia -> Spell combo...?

**Comment by AkiraChisaka** [comment]
Also is it possible for the Sage's unique Kardia spells to be bounded on buttons?

So like, replace a emote into the Kardia -> Spell combo...?

Basically replace something so that when pressing it, it is first Kardia, then the spell.

Might not be feasible.

**Comment by daemitus** [comment]
since kardia replaces the other spells, im not sure why we'd want to

**Comment by AkiraChisaka** [comment]
Yeah, it's a pretty dumb idea, I'm probably not gonna even use the feature lol.

But the idea is to have a way to bind Eukrasian Dosis, Eukrasian Diagnosis, and Eukrasian Prognosis onto the hotbar. So that when you press the keybind, you will first automatically use Kardia, then the corresponding spell when you press it a second time.

But yeah, not sure if anyone will actually need this.

**Comment by daemitus** [comment]
@AkiraChisaka So im reading raiju goes away if you use a weaponskill. So in theory, you could continue to use mudras and hold the ability. 

So either replace the default 1-2-3 combos, or maybe re-use Huraijin? I can't imagine wanting to  lose your gigantic finisher to  re-up suiton.

**Comment by AkiraChisaka** [comment]
Hmm, I'm actually pretty sure that Raiju don't go away when you do random stuff.

As in, using Raiton gives Raiju ready for 30 sec. Then you can go do random stuff, then come back to do Raiju as long as you still have the buff.

I don't think I saw anywhere that Raiju disappear if you use Weaponskills, since Raiju Ready is just a buff on you, not a combo.

**Comment by daemitus** [comment]
was watching the mr happy NIN video on the changes, specifically mentioned it. We'll see once the expac actually drops.

I think im done with the easy stuff for now. the top comment has been updated appropriately.

**Comment by AkiraChisaka** [comment]
I see, I haven't actually seen it used before. I guess this means combo do break it.

**Comment by serratedhalo** [comment]
All of these are off the GCD abilities that just have varying cooldowns.  They essentially all do the same thing and qualify for one button features imo:

Paladin
Circle of Scorn and Spirits Within on one button.

Dark Knight
Salted Earth, Abyssal Drain, Carve and Spit on one button.  (Salted earth wont be a targeted circle in EW so wont have to worry about placing it)

Dragoon
Dragonfire Dive and Spineshatter Dive on one button.

Bard
Empyreal Arrow, Bloodletter, and Sidewinder on one button.
Empyreal Arrow, Rain of Death, and Shadowbite on one button.
(If Empyreal Arrow can't be in two different buttons, I'd centralize it with Bloodletter and Sidewinder since its single target)

Red Mage
Fleche and Contre Sixte on one button.

**Comment by AmenneHolelane** [comment]
> WAR.     NEW WarriorPrimalRendFeature: Inner Beast and Steel Cyclone into Primal Rend when available.

i'd argue that primal rend should go on IR as it's a buff from IR that grants it, also you can still use nascent chaos and IR actions without burning rend

**Comment by IGP** [comment]
Sage:
- Addersgall spenders (Druochole, Taurochole, Ixochole, Kerachole) become Rhizomata when you have 0 Addersgall.
- Soteria becomes Kardia when Kardia is not active

**Comment by daemitus** [comment]
Regarding ogcd all-in-one buttons, i made some, but cooldown tracking is jacked when charges get involved unless all skills have the same amount.  For example, MCH works fine, but DRG doesn't work right, because it counts internally from 120, even if you only have 1 charge, before the trait. It'll take some more research to figure out an alternative. 

Regarding rend: You're gonna press it anyways and since it doesn't count against IR stacks, its more of a which button do you want to press first?

sage stuff: problem for later. got other plugins that need dealing  with.

Likely going to release this tomorrow night, let any other bug reports that people have filter in.

**Comment by 0kie** [comment]
As a NIN main I can confirm that Raiju does goes away if you use a weaponskill (basically any gcd), replacing the 1-2-3 combos with Raiju would be super useful, more than replacing Huraijin.

**Comment by daemitus** [comment]
I've added additional options to add it to both 1-2-3 combos
