### ISSUE TITLE
[BLM] [Bug/Issue] Fire 2 Feature does not work properly

### ISSUE THREAD

**Issue by HuNtOziO** [daemitus/XIVComboPlugin#128]
Description of intended feature and how it should work is:
"(High) Fire 2 becomes Flare in Astral Fire with 1 or fewer Umbral Hearts."

However it doesn't work like this, fire 2/high fire 2 swaps to flare when you still have 2 stacks of Umbral Hearts, meaning it swaps the ability 1 stack too early meaning you lose AOE dps as you will end up being outside of astral fire mode sooner.

Thought I'd put it here so it can get fixed in a future update, so it swaps high fire 2 to flare when you have one umbral heart stack left

Thank you for this amazing plugin though! 😄

**Comment by Grammernatzi** [comment]
You actually lose aoe dps if you triple Fire 2 instead of High Fire 2, but I digress. Since you need Flare manually on your bare if you want to do triple HF3s, you should not use this option, otherwise you will actually lose aoe damage if you always use 3 HFs if either mobs are about to die, or if you have triplecast up. I'd just recommend turning the feature off if you care about it. Otherwise, he was going to add an option for particularly picky people, but

**Comment by HuNtOziO** [comment]
Oh interesting, I'll have to look into that thanks! A back mage aoe guide I saw may have been incorrect then 😅 eek!! Thank you 👍
