### ISSUE TITLE
[PLD] Drop the Atonement Feature after 2nd Atonement.

### ISSUE THREAD

**Issue by Vec7rex** [daemitus/XIVComboPlugin#138]
it would be great if it were possible to drop the atonement feature after 2nd atonement while enemy has "Blade of Valor" buff.
thanks for your neat plugins.

**Comment by Grammernatzi** [comment]
You can still start the combo with the Goring Blade/Royal Authority combo (whichever you don't have the Atonement Feature on), so you can manually ignore atonement. That way it'll still work when synced as well.

**Comment by SashaFFXIV** [comment]
> You can still start the combo with the Goring Blade/Royal Authority combo (whichever you don't have the Atonement Feature on), so you can manually ignore atonement. That way it'll still work when synced as well. You can also use /statusoff "Sword Oath" on a macro, too.

The problem is for optimization PLD often drops an unbuffed Atonement. If you use the Goring Blade Atonement Feature you cannot do this because Atonement replaces the Goring Blade.

Cannot continue my combo into Goring Blade:

![image](https://user-images.githubusercontent.com/55117631/154959969-07ca3fa2-5b88-49ae-bcd5-1414beee7ea8.png)

 OP is suggesting that if the enemy has the Blade of Valor debuff it should disable the feature after using 2 Atonements as that is the point in your rotation where you drop the unbuffed Atonement. This should be easy to implement, if the enemy has Blade of Valor applied to them then the feature should disable upon reaching 1 stack of Sword Oath instead of 0.

**Comment by daemitus** [comment]
"often" or "always"

**Comment by SashaFFXIV** [comment]
As far as I know you should always be dropping an unbuffed Atonement.

**Comment by Grammernatzi** [comment]
On my own fork I fixed this issue by having it so that the Goring Blade atonement feature only works while you're currently not in a combo. So you can easily restart the combo with Fast Blade and Goring Blade stops being replaced by Atonement. The same change would probably work here. I actually wasn't aware it didn't work that way here, that explains things.

**Comment by daemitus** [comment]
done
