### ISSUE TITLE
Twin Snakes(monk)

### ISSUE THREAD

**Issue by proulus** [daemitus/XIVComboPlugin#139]
would be great if Twin Snakes didn't turn into True Strike if the formless fist buff is up as you use that pretty often after and it's usually a second or two waiting for the timer to switch

**Comment by kaedys** [comment]
IIRC, Twin Snakes only turns into True Strike if Twin Snakes has >6s remaining on the duration.  The entire sequence of Perfect Balance takes at most 8 seconds to complete, and you'd want to wait to refresh Twin Snakes until later in a Perfect Balance sequence anyway, if you're doing the Solar sequence (one of each form).  So if it's during Perfect Balance, you're either waiting to use True Strike until later in the sequence of 3 abilities, or the buff will last longer than the PB sequence anyway.  And if you're talking about the Formless Fist buff _after_ PB, you're usually going back into your normal sequence at that point, and the 6s threshold is more than the time it takes to cycle through all 3 forms and get back to Twin Snakes again anyway.

Unconditionally using Twin Snakes during Formless Fist would be, imo, a bit odd, as you certainly wouldn't want to use Twin Snakes if you had, say, 12s still left on the buff.  Still, the majority of the time, you're using Formless Fist on Dragon Kick or Bootshine, because cycling those faster is generally the goal, and I know the "standard" Balance rotation uses an abnormal Twin Snakes via Formless Fist after PB on every 3rd usage just to get a nice clean looping rotation (which I personally think is a bit silly, but w/e), so I don't really see an issue with an option for always using Twin Snakes during Formless Fist, since using Formless Fist on True Strike over DK/BS is...basically a hard no-no.

**Comment by daemitus** [comment]
option added.
