### ISSUE TITLE
(RPR) Guillotine replace Grim Swathe

### ISSUE THREAD

**Issue by Maya1924** [daemitus/XIVComboPlugin#161]
Can we have an option for Guillotine to replace Grim Swathe when Reaving or Enshrouded? And then have Lemure's Scythe show up in that chain while Enshrouded as well, if you could!

**Comment by kaedys** [comment]
Right now, Guillotine (optionally) replaces the standard AoE buttons, and can optionally include Lemure's Scythe in that already.  Why replace Grim Swathe with it instead?  The standard AoE combo is a more natural position for it, imo, since you're already used to spamming that button for the AoE combo.

**Comment by daemitus** [comment]
reaper code is already a bit of a spaghetti mess with all the options everywhere. I don't see much of a need for this.
