### ISSUE TITLE
this combo is obsolete (kinda?)

### ISSUE THREAD

**Issue by AmenneHolelane** [daemitus/XIVComboPlugin#17]
https://github.com/daemitus/XIVComboPlugin/blob/3de8778aa511426b66c560e56ca094d68ec8c02f/XIVComboExpanded/Combos/WAR.cs#L140

i think this is still valid cuz you still get nascent synced away so having raw there for memory issues is nice. it shouldn't make a huge difference re: bloodletter as that's replacing raw at 82+ i think.... thoughts?

**Comment by daemitus** [comment]
it likely is to an extent, it was originally added for a muscle memory while sync'd request. 

Since nascent is self-only you probably need both on your bar from now on regardless.

**Comment by kaedys** [comment]
Recommend:

* Bloodwhetting if >= 82
* Nascent Flash if >= 76 and < 82
* Raw Intuition if < 76

Nascent Flash unfortunately requires a friendly target (I have that fixed with a macro that casts Nascent Flash on my focus, then party 2 (the other tank, or the healer in a 4-man), then chocobo, then simply the nearest player), but it's still a _wildly_ superior defensive in nearly all cases between 76 and 81.  Not sure if you want to get into the auto-target territory (that feels like it might belong more in MOActions, which is normally what I use for it, except that MOActions hasn't yet been updated), but if so, all the better.  Either way, I feel like having this option gracefully fall back through Nascent Flash would be a good way to do it.  And also, incidentally, not something a macro can do, since trying to cast Bloodwhetting via /ac when under 82 casts Raw Intuition instead., so you can't just do one that tries to cast Bloodwhetting, then Nascent Flash, then Raw Intuition.

Also, not sure what you mean by this:

> Since nascent is self-only you probably need both on your bar from now on regardless.

Nascent is friendly target only.  You actually _can't_ cast it on yourself.  But the heal you gain from casting it on a friendly is strong enough that it's almost always better than Raw Intuition during the relevant level range (ie. before you get Bloodwhetting, which has the same effect, except it also grants you a shield and an additional 10% DR for the first half of the effect (Nascent gets upgraded to grant those benefits to your target, not you).

**Comment by AmenneHolelane** [comment]
raw and bloodwhetting are a direct upgrade, no need to do anything with that. the existing swap Nascent with Raw when sub 76 is all you need to do lol. use a macro/MOAction for anything else as that's what they were designed to do

**Comment by kaedys** [comment]
Not really.  Bloodwhetting adds the effects of Nascent _into_ Raw.  And between 76 and 82, when you have Nascent but not Bloodwhetting, Nascent is nearly _always_ better than Raw.  So between those levels, you need to swap to a different keybind for your defensive, because you should be using Nascent, not Raw.  The only time Raw beats Nascent in that band is if the damage would otherwise kill you.

And in AoE, it's no contest, since the 400 potency heal is _per target_.  You literally fully heal with each AoE attack when Nascent is up.

**Comment by kaedys** [comment]
@daemitus recommend taking a look at this issue when you get the chance

**Comment by AmenneHolelane** [comment]
raw/bloodwhetting and nascent need to be two separate as they serve two different but valid uses. if you're a level 77 WAR doing something solo and you can't hit the fucking raw intuition button, you're fucked. Raw intuition literally says in the tooltip that it heals you for every weaponskill delivered so how exactly is Nascent better than Raw in an AoE pull?

**Comment by AmenneHolelane** [comment]
Raw Intuition would actually be better because not only are you healing yourself, you're also taking less damage.

**Comment by kaedys** [comment]
I stand corrected.  I had not noticed they'd added the heal to Raw Intuition alongside Bloodwhetting.  I was still in pre-EW mode, where Nascent just flat out took over for Raw in most cases once you got it.  You're correct, Raw Intuition is strictly superior to Nascent now (finally >.>).  I retract my suggestion.
