### ISSUE TITLE
Request: Paladin updates

### ISSUE THREAD

**Issue by Kylis** [daemitus/XIVComboPlugin#197]
A couple of new paladin feature requests with the rework

Replace Royal Authority/Prominence with Holy Spirit/Holy Circle respectively when under the effects of Divine Might.
Replace Goring Blade with Fight or Flight (they have the same cooldown and Goring Blade is now just a burst cooldown now)
Change Confiteor feature as you don't use requiescat on Holy Spirit/Circle anymore. (rotation image for reference)
[https://xiv.sleepyshiba.com/pld/img/63-60stentative2.png](url)
Change Requiescat Confiteor to chaining the whole blade combo while Requiescat is up.

**Comment by Grammernatzi** [comment]
Replacing royal authority with holy spirit is a bad idea because you need to restart your combo for some rotations before using holy spirit. The rest are fine. But I've done the theorycrafting myself and currently the best way to keep holy spirit/atonement/royal authority combo atm is as 3 separate buttons, as you have to press them out of order constantly (you want to save holy spirit for FoF if it's close, for instance, while also getting your combo right up to before Royal Authority). I've talked with Dae and he agrees, and he's going to update the plugin, he just needs some time.

**Comment by Kylis** [comment]
Ah ok, makes sense.

**Comment by Grammernatzi** [comment]
Well, we can add it so that it turns into Holy Spirit right before you would press Royal Authority; that wouldn't get in the way of anything, and would be similar to how it works on GNB. I'm going to help update it at the moment since Daemitus isn't subbed, he said it was alright.

**Comment by Kylis** [comment]
The requiescat confiteor combo would be nice if it continued into the blade combo after confiteor was used.

**Comment by Grammernatzi** [comment]
It should work like that, shouldn't it? It does in the code, and it did when I tested it.

**Comment by kaedys** [comment]
Can confirm that neither the Holy Circle -> Blade chain or Req -> Blade chain features are working as expected.  They work with Confiteor, but then stop after that.  It appears as if Confiteor + Blade chain is now implements similar to the GNB Gnashing Fang chain, where it's _sorta_ a combo, but not really, because it doesn't interfere with existing combo chains (ex. Royal Authority).  Confiteor itself naturally swaps between them, though, so similar to the GNB Gnashing Fang feature, where it just returns `OriginalHook(GNB.GnashingFang)` for all 3 combo moves and lets the game handle the swap, I suspect you can do the same here with Confiteor, just return `OriginalHook(PLD.Confiteor)` and let the game figure it out.

**Comment by daemitus** [comment]
Figures that they didnt make it an actual combo action.

**Comment by kaedys** [comment]
Tested both features, both are working as expected now.
