### ISSUE TITLE
Sage stuff

### ISSUE THREAD

**Issue by IGP** [daemitus/XIVComboPlugin#24]
Taken from #11 

Sage:
- Addersgall spenders (Druochole, Taurochole, Ixochole, Kerachole) become Rhizomata when you have 0 Addersgall
   - Rhizomata gives you an Addersgall
- Soteria becomes Kardia when Kardia is not active
   - Soteria buffs Kardia, pointless without Kardia
- Pepsis helper, block casting of Pepsis if no party members or self in range have Eukrasian Diagnosis or Eukrasian Prognosis
   - Pepsis has no effect if no party member in range/self has Eukrasian Diagnosis or Eukrasian Prognosis

These are not for reducing button counts (you would still want all the above on individual keys) but more to prevent/catch scenarios where you would be unable to utilize the affected skills otherwise.

**Comment by Jaesaces** [comment]
I'll add "Replace Druochole with Taurochole when Taurochole is ready" to these suggestions.

**Comment by Zynyx** [comment]
I get this class is a bit harder to work with because of Eukrasian combos, not sure if any of these can be done but I'll lay them out there:

1. **Kerachole & Physis II** - Both are short CD (30s and 60s respectively) AoE heals with slightly different affects, but if it could be made to use Kerachole when available & Physis II when Kerachole is on CD I think that'd be an overall quality of life gain and a button saved.

Will Edit and add more later.

**Comment by Zynyx** [comment]
Did any of this go live? My addon is up to date and I still see no sage options in the settings.

**Comment by daemitus** [comment]
not as of yet, ive been pretty busy and havent touched the job yet.

**Comment by Zynyx** [comment]
Take your time and thanks for everyone's hard work. :) Just making sure I wasn't the issue.

**Comment by daemitus** [comment]
pepsis won't happen, scanning for actors is a major resource hog. the rest should be in. open an issue if i fucked up the implementation
