### ISSUE TITLE
(RDM) Red Mage AoE Combo does not switch to Scatter.

### ISSUE THREAD

**Issue by tommy8492nd** [daemitus/XIVComboPlugin#34]
As of this post, neither spell transitions automatically into Scatter.
I am only Level 61, so I cannot test if it still works with Impact.

**Comment by Grammernatzi** [comment]
`if (level >= RDM.Levels.Impact && (HasEffect(RDM.Buffs.Dualcast) || HasEffect(RDM.Buffs.Acceleration) || HasEffect(RDM.Buffs.Swiftcast) || HasEffect(RDM.Buffs.LostChainspell)))
                    return OriginalHook(RDM.Impact);`

It seems to be because it wrongly checks for Impact's level, when it should instead be checking for Scatter's. Or just none at all, because you can't even use verthunder 2/veraero 2 before you get Scatter.

**Comment by tommy8492nd** [comment]
It seemed to work before the last update.
Perhaps a regression bug?

**Comment by daemitus** [comment]
yeah a regression. I've been wanting to sort of standardize the checks and check some sort of level. changed to scatter in .19

**Comment by PrincessRTFM** [comment]
IIRC (game's not open right now) Scatter without Acceleration never does more damage than Veraero/Verthunder 2 do. If that's the case, is Scatter really more useful than just casting both of the others back-to-back?

**Comment by Grammernatzi** [comment]
Scatter does more damage, veraero/thunder 2 do 100 potency when you have
scatter. Their potency does not get upgraded until after you have impact.

**Comment by daemitus** [comment]
does the combo need to be tweaked between certain level ranges?

**Comment by Grammernatzi** [comment]
No, I have already reviewed it myself in the past and it's fine as it is.
