### ISSUE TITLE
BLM Fire 2 feature suggestion

### ISSUE THREAD

**Issue by Cadwgan** [daemitus/XIVComboPlugin#74]
During BLMs AoE rotation using a 3rd (High) Fire 2 is a DPS loss overall, suggestion would be to change (High) Fire 2 to Flare when wither 1 or fewer Umbral Hearts or Enhanced Flare buff is active.

**Comment by Grammernatzi** [comment]
Is this true? [The Balance still has 3 High Fire 2s listed for their AoE rotation.](https://docs.google.com/document/d/11ZY8zAoz9T8doy8Z_D_UXGiReCp7LMl-HsLlHjYhng8/edit) Not saying you're wrong, I'm just curious.

**Comment by Cadwgan** [comment]
On paper it's a flat DPS loss, but overall it depends on how long mob packs last and how many targets you're hitting, a 3rd HF2 might yield slightly higher damage but the majority of the time the time the packs should be dying as you're finishing your 2nd round of flares, which a 3rd (H)F2 delays.

Basically, a 3rd F2 is absolutely a DPS loss, a 3rd HF2 is "will these dye in the middle of my next fire phase?" which most of the time is yes unless the rest of the party isn't AoEing.

**Comment by Grammernatzi** [comment]
Fair enough, and I feel like in AoE, which is mostly just used in Dungeons and very short phases in fights, can afford to have features that work well 95% of the time, especially if that remaining 5% isn't really much worse. So that seems like a good enough choice to add since I feel like if someone was really anal about it, they wouldn't be using this feature in the first place.

**Comment by daemitus** [comment]
```
if (level >= BLM.Levels.Flare && gauge.InAstralFire && (gauge.UmbralHearts == 1 || LocalPlayer?.CurrentMp < 3800 || HasEffect(BLM.Buffs.EnhancedFlare)))
    return BLM.Flare;
```

available next push.

**Comment by Grammernatzi** [comment]
I mean, I did check and the DPS increase is very slight, and gets invalidated if enemies would die before the second flare or you have triplecast (which would be yet even more logic to check for). Since this is just for trash anyway, it'd probably be fine. If you're the kind of person who wants to min max this sort of thing for the tiny potency per second gain, you probably shouldn't have this feature on anyway.
