### ISSUE TITLE
BLM Transpose Firestarter Proc

### ISSUE THREAD

**Issue by lhn1703** [daemitus/XIVComboPlugin#86]
Transpose -> Umbral Soul if in Umbral Ice and no firestarter proc. Transpose from Umbral Ice followed by firestarter proc is an very easy transpose line with free potency.

**Comment by Grammernatzi** [comment]
Honestly I would just turn the feature off at this point, especially since it conflicts with paradox transpose which is very useful for movement at level 90. Maybe an option that has umbral soul turn into transpose rather than the other way around, so you can still have both on your bar but one button changes depending on the situation.

**Comment by lhn1703** [comment]
I agree on changing umbral soul into transpose, it is a more straightforward solution.

**Comment by daemitus** [comment]
what is umbral just switched back to transpose if you were at 3 hearts?

**Comment by kaedys** [comment]
Umbral is also used while at 3 hearts during downtime or heavy movement, to keep Ice active, though (ex. when running between trash pulls in an instance, so you can immediately start the next pull with Fire 3 or High Fire 2 instead of your ice combo).  I think having Umbral change into Transpose when Umbral isn't usable (and _only_ when it strictly is not usable, ie. too low level or not in Umbral Ice) is the most flexible.  It let's Umbral Soul be used as the "standard" button for swapping into and keeping UI active, and then Transpose itself can still be on the bar for when the user desires to intentionally Transpose into Fire (something that is otherwise relatively unusual once you learn Umbral Soul, and has sufficient conditions that I think it'd make more sense for the user to decide to do it).

**Comment by lhn1703** [comment]
Actually, the recent ice spells -> umbral soul when no target feature provides a good alternative solution to this issue. The only suggestion I could make to that feature to lump umbral upkeep into 1 button during downtime is:

if (no target available && in astral fire) ice spells -> transpose
else if (no target available && in umbral ice) ice spells -> umbral soul

The original issue was made with the intention of high end optimizations for raids, which have more or less been circumvented. I will no longer use the current transpose -> umbral soul feature, but it is still applicable to those who do not optimize with transpose.
